// Objective-C API for talking to github.com/s3ntin3l8/branchdam-mobile Go package.
//   gobind -lang=objc github.com/s3ntin3l8/branchdam-mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Branchdam_H__
#define __Branchdam_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class BranchdamEngine;
@class BranchdamEngineOptions;
@class BranchdamEnqueueMediaOptions;
@class BranchdamError;
@class BranchdamHashes;
@class BranchdamSafeSpaceCandidate;
@class BranchdamSafeSpaceVerdict;
@class BranchdamSyncOptions;
@class BranchdamSyncResult;

/**
 * Engine is the long-lived handle to a branchdam session. It owns the
SQLite queue, the HTTP client, and the underlying core engine. All
exported methods are safe to call from multiple goroutines; the
underlying queue is serialized through its own mutex.

Event payload size cap: events enqueued through this Engine
(EnqueueLineageEvent, EnqueueDeleteEvent) are bounded at
queue.MaxEventPayloadBytes (64 KiB). The cap prevents a single
misbehaving caller from writing a multi-MB payload to the event
queue, which would otherwise lock the queue's single SQLite
connection and stall every other writer. Oversized input is
rejected with INVALID_INPUT before any row is inserted; do NOT
raise the cap or add a code path that bypasses it.
 */
@interface BranchdamEngine : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor Engine.NewEngine with unsupported parameter or return types

// skipped method Engine.CheckSafeSpaceCandidates with unsupported parameter or return types

/**
 * Close releases the SQLite database. Idempotent; calling Close on an
already-closed Engine returns nil.
 */
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
// skipped method Engine.ComputeHashes with unsupported parameter or return types

- (BOOL)countPendingUploads:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)enqueueDeleteEvent:(NSString* _Nullable)localID error:(NSError* _Nullable* _Nullable)error;
// skipped method Engine.EnqueueLineageEvent with unsupported parameter or return types

// skipped method Engine.EnqueueMedia with unsupported parameter or return types

- (NSString* _Nonnull)fetchNamingTemplate:(NSError* _Nullable* _Nullable)error;
// skipped method Engine.GetActiveUploadProgress with unsupported parameter or return types

// skipped method Engine.GetAllMediaStatuses with unsupported parameter or return types

- (NSString* _Nonnull)getMediaStatus:(NSString* _Nullable)localID error:(NSError* _Nullable* _Nullable)error;
- (BOOL)isMediaOffloaded:(NSString* _Nullable)localID ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
// skipped method Engine.Options with unsupported parameter or return types

// skipped method Engine.ReclaimSafeSpace with unsupported parameter or return types

- (BOOL)resetFailedUploads:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setCancelFlag:(NSError* _Nullable* _Nullable)error;
- (BOOL)setMediaOffloaded:(NSString* _Nullable)localID isOffloaded:(BOOL)isOffloaded error:(NSError* _Nullable* _Nullable)error;
// skipped method Engine.SyncBatch with unsupported parameter or return types

@end

/**
 * EngineOptions configures a new Engine. Validation is performed at
NewEngine time only; methods on a successfully-constructed Engine assume
the options are valid.
 */
@interface BranchdamEngineOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull dbPath;
@property (nonatomic) NSString* _Nonnull baseURL;
@property (nonatomic) NSString* _Nonnull apiKey;
@property (nonatomic) NSString* _Nonnull agentID;
@property (nonatomic) NSString* _Nonnull clientVersion;
@property (nonatomic) long httpTimeoutSec;
// skipped field EngineOptions.DevCleartextHosts with unsupported type: []string

@end

/**
 * EnqueueMediaOptions configures a single media enqueue.
 */
@interface BranchdamEnqueueMediaOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull localPath;
@property (nonatomic) NSString* _Nonnull filename;
@property (nonatomic) NSString* _Nonnull localID;
@property (nonatomic) NSString* _Nonnull cameraModel;
@property (nonatomic) NSString* _Nonnull sourcePathHash;
@property (nonatomic) int64_t capturedAtUnix;
@property (nonatomic) int64_t sizeBytes;
@end

/**
 * Error is a structured error type for the branchdam FFI surface. The Code
field is the source of truth for programmatic handling; the Message
field is a human-readable explanation suitable for logs.
 */
@interface BranchdamError : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull code;
@property (nonatomic) NSString* _Nonnull message;
/**
 * Error implements the error interface.
 */
- (NSString* _Nonnull)error;
@end

/**
 * Hashes is the result of a streaming BLAKE3 + xxHash over a local file.
 */
@interface BranchdamHashes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull blake3;
@property (nonatomic) NSString* _Nonnull fast;
@end

/**
 * SafeSpaceCandidate describes a local media item the shell is asking the
engine to evaluate for safe reclamation.
 */
@interface BranchdamSafeSpaceCandidate : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull localID;
@property (nonatomic) NSString* _Nonnull nodeUUID;
@property (nonatomic) NSString* _Nonnull blake3Hash;
@property (nonatomic) NSString* _Nonnull tier;
@property (nonatomic) BOOL isVerified;
@property (nonatomic) BOOL isEligible;
@end

/**
 * SafeSpaceVerdict is the engine's per-candidate verdict.
 */
@interface BranchdamSafeSpaceVerdict : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull localID;
@property (nonatomic) BOOL eligible;
@property (nonatomic) NSString* _Nonnull reason;
@end

/**
 * SyncOptions controls a SyncBatch call.
 */
@interface BranchdamSyncOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long timeoutSecs;
@property (nonatomic) long batchSize;
@property (nonatomic) int64_t retryBackoffSecs;
@property (nonatomic) long maxRetries;
@property (nonatomic) BOOL includeEvents;
@property (nonatomic) BOOL includeUploads;
@end

/**
 * SyncResult reports what SyncBatch did. Counts are best-effort; if the
batch is cancelled mid-flight the partial counts are returned with
CONTEXT_CANCELED.
 */
@interface BranchdamSyncResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t uploaded;
@property (nonatomic) int64_t eventsSent;
@end

/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeContextCanceled;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeDBError;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeDedupNoNodeUUID;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeHashMismatch;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeIOError;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeInvalidInput;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeNetworkError;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodePayloadTooLarge;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeResponseTooLarge;
/**
 * Common error codes returned by the Engine. Shells should match on Code,
not Message, since the latter is subject to change.
 */
FOUNDATION_EXPORT NSString* _Nonnull const BranchdamCodeVerifiedRequired;
// skipped const ConfidenceEdit with unsupported type: github.com/s3ntin3l8/branchdam-mobile.Confidence

// skipped const ConfidenceExact with unsupported type: github.com/s3ntin3l8/branchdam-mobile.Confidence

// skipped const ConfidenceProximity with unsupported type: github.com/s3ntin3l8/branchdam-mobile.Confidence


@interface Branchdam : NSObject
/**
 * ErrProgressAborted is returned by ComputeHashes when the ProgressFunc
returns false.
 */
+ (NSError* _Nullable) errProgressAborted;
+ (void) setErrProgressAborted:(NSError* _Nullable)v;

@end

/**
 * BindingCheckContent calls GET /api/v1/agent/check-content with the given
hashes. Returns a JSON-encoded ContentCheckResult string, or "" on error.
Follows the BindingCheckSafeSpaceCandidates pattern for gomobile compatibility.
Uses a 30-second timeout to prevent ANR on mobile if the server is slow.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingCheckContent(NSString* _Nullable fastHash, NSString* _Nullable fullHash, NSError* _Nullable* _Nullable error);

/**
 * BindingCheckSafeSpaceCandidates checks a batch of local IDs for
eligibility. localIDs is a comma-separated list. Returns a
comma-separated "localID:eligible:reason" string.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingCheckSafeSpaceCandidates(NSString* _Nullable localIDs, NSError* _Nullable* _Nullable error);

/**
 * BindingClose closes the engine and releases resources.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingClose(NSError* _Nullable* _Nullable error);

/**
 * BindingComputeHashes streams localPath and returns its 64-hex-char BLAKE3-256
digest. Used by the OTG ingest post-copy verification (T2-7) so the shell can
detect a corrupt SD card mid-copy without keeping a second BLAKE3
implementation in sync with the upload-side hash. Returns "" on error;
callers should treat that as "hash unavailable, defer to upload-side".
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingComputeHashes(NSString* _Nullable localPath, NSError* _Nullable* _Nullable error);

/**
 * BindingCountPendingUploads returns the number of pending/in-progress uploads in the queue.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingCountPendingUploads(int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * BindingEnqueueDeleteEvent enqueues a local-delete lifecycle event.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingEnqueueDeleteEvent(NSString* _Nullable localID, NSError* _Nullable* _Nullable error);

/**
 * BindingEnqueueLineageEvent enqueues a lineage relationship event.
confidence is a 0.0–1.0 score.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingEnqueueLineageEvent(NSString* _Nullable parentLocalID, NSString* _Nullable childLocalID, NSString* _Nullable relationshipType, NSString* _Nullable resolver, double confidence, NSError* _Nullable* _Nullable error);

/**
 * BindingEnqueueMedia enqueues a local media file for upload without an explicit source path hash.
Returns the upload ID (>= 1) on success or 0 on error.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingEnqueueMedia(NSString* _Nullable localPath, NSString* _Nullable filename, NSString* _Nullable localID, NSString* _Nullable cameraModel, int64_t capturedAtUnix, int64_t sizeBytes, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * BindingEnqueueMediaWithSourceHash enqueues a local media file for upload with an explicit sourcePathHash.
Returns the upload ID (>= 1) on success or 0 on error.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingEnqueueMediaWithSourceHash(NSString* _Nullable localPath, NSString* _Nullable filename, NSString* _Nullable localID, NSString* _Nullable cameraModel, NSString* _Nullable sourcePathHash, int64_t capturedAtUnix, int64_t sizeBytes, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * BindingFetchNamingTemplate fetches the naming template from the server.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingFetchNamingTemplate(NSError* _Nullable* _Nullable error);

/**
 * BindingGetActiveUploadProgress returns JSON string of active upload metrics, or "" if none.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingGetActiveUploadProgress(NSError* _Nullable* _Nullable error);

/**
 * BindingGetAllMediaStatuses returns a JSON-encoded map of localID/localPath/srcPathHash -> status.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingGetAllMediaStatuses(NSError* _Nullable* _Nullable error);

/**
 * BindingGetMediaStatus returns the status of a local media asset.
Returns "OFFLOADED", "COMPLETED", "IN_PROGRESS", "PENDING", "FAILED", or "NOT_ENQUEUED".
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingGetMediaStatus(NSString* _Nullable localID, NSError* _Nullable* _Nullable error);

/**
 * BindingIsMediaOffloaded returns the offload flag. On error returns false
(fail-closed: shell refuses to delete).
 */
FOUNDATION_EXPORT BOOL BranchdamBindingIsMediaOffloaded(NSString* _Nullable localID, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * BindingLookupBlake3ForLocalID returns the BLAKE3-256 hash most recently
recorded against localID in the local_media_state table, or "" if the
localID is unknown. Used by the OTG ingest pipeline to detect the case
where the same localID has been ingested before and produced a different
hash — typically a sign that the source SD card is failing and the bytes
have changed since the previous scan. The shell logs a warning when this
happens but continues with the new hash (the source-of-truth is the file
on disk, not the prior queue entry).
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingLookupBlake3ForLocalID(NSString* _Nullable localID, NSError* _Nullable* _Nullable error);

/**
 * BindingOpen initialises the engine from primitive parameters.
devCleartextHosts is a comma-separated list of hosts allowed over
HTTP in debug builds; pass "" in production to require HTTPS.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingOpen(NSString* _Nullable dbPath, NSString* _Nullable baseURL, NSString* _Nullable apiKey, NSString* _Nullable agentID, NSString* _Nullable clientVersion, NSString* _Nullable devCleartextHosts, NSError* _Nullable* _Nullable error);

/**
 * BindingReclaimSafeSpace runs the atomic reclaim for a single local ID.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingReclaimSafeSpace(NSString* _Nullable localID, NSError* _Nullable* _Nullable error);

/**
 * BindingResetFailedUploads resets all FAILED upload items back to PENDING.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingResetFailedUploads(int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * BindingSetCancelFlag requests cancellation of the current sync batch.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingSetCancelFlag(NSError* _Nullable* _Nullable error);

/**
 * BindingSetMediaOffloaded sets the offload flag directly.
 */
FOUNDATION_EXPORT BOOL BranchdamBindingSetMediaOffloaded(NSString* _Nullable localID, BOOL isOffloaded, NSError* _Nullable* _Nullable error);

/**
 * BindingSyncBatch runs a sync cycle. Returns "uploaded,eventsSent" string on success.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamBindingSyncBatch(int64_t timeoutSecs, int64_t batchSize, NSError* _Nullable* _Nullable error);

// skipped function NewEngine with unsupported parameter or return types


/**
 * Version is the package's reported build version. Smoke-test helper for
shells verifying artifact loading. The canonical version lives in the
release-please manifests; this value is a build-time stub.
 */
FOUNDATION_EXPORT NSString* _Nonnull BranchdamVersion(void);

#endif
