package com.branchdam.mobile.ui.theme

import androidx.compose.ui.graphics.Color

// Brand Teal: #2BA69A (derived from iOS BrandMonogramView)
val BrandTeal = Color(0xFF2BA69A)

// Material 3 Tonal Palette derived from Brand Teal (#2BA69A)
// Generated for Light Scheme
val PrimaryLight = Color(0xFF006A62)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF71F7E9)
val OnPrimaryContainerLight = Color(0xFF00201D)
val SecondaryLight = Color(0xFF4A635F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E3)
val OnSecondaryContainerLight = Color(0xFF05201C)
val TertiaryLight = Color(0xFF446279)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC9E6FF)
val OnTertiaryContainerLight = Color(0xFF001E2F)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF4FBFA)
val OnBackgroundLight = Color(0xFF161D1C)
val SurfaceLight = Color(0xFFF4FBFA)
val OnSurfaceLight = Color(0xFF161D1C)
val SurfaceVariantLight = Color(0xFFDAE5E2)
val OnSurfaceVariantLight = Color(0xFF3F4947)
val OutlineLight = Color(0xFF6F7977)
val OutlineVariantLight = Color(0xFFBEC9C7)
val ScrimLight = Color(0xFF000000)
val InverseSurfaceLight = Color(0xFF2B3231)
val InverseOnSurfaceLight = Color(0xFFECF2F1)
val InversePrimaryLight = Color(0xFF50DBCB)

// Generated for Dark Scheme
val PrimaryDark = Color(0xFF50DBCB)
val OnPrimaryDark = Color(0xFF003733)
val PrimaryContainerDark = Color(0xFF00504A)
val OnPrimaryContainerDark = Color(0xFF71F7E9)
val SecondaryDark = Color(0xFFB1CCC7)
val OnSecondaryDark = Color(0xFF1C3531)
val SecondaryContainerDark = Color(0xFF324B47)
val OnSecondaryContainerDark = Color(0xFFCCE8E3)
val TertiaryDark = Color(0xFFACCAE5)
val OnTertiaryDark = Color(0xFF133348)
val TertiaryContainerDark = Color(0xFF2C4A60)
val OnTertiaryContainerDark = Color(0xFFC9E6FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0E1514)
val OnBackgroundDark = Color(0xFFDDE4E2)
val SurfaceDark = Color(0xFF0E1514)
val OnSurfaceDark = Color(0xFFDDE4E2)
val SurfaceVariantDark = Color(0xFF3F4947)
val OnSurfaceVariantDark = Color(0xFFBEC9C7)
val OutlineDark = Color(0xFF899391)
val OutlineVariantDark = Color(0xFF3F4947)
val ScrimDark = Color(0xFF000000)
val InverseSurfaceDark = Color(0xFFDDE4E2)
val InverseOnSurfaceDark = Color(0xFF2B3231)
val InversePrimaryDark = Color(0xFF006A62)
