
// Objective-C API for talking to the following Go packages
//
//	github.com/s3ntin3l8/branchdam-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Branchdam_FRAMEWORK_H__
#define __Branchdam_FRAMEWORK_H__

#include "Branchdam.objc.h"
#include "Universe.objc.h"

#endif
