package com.branchdam.mobile

import com.branchdam.mobile.ui.settings.EngineInit
import com.branchdam.mobile.ui.settings.SettingsViewModel
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

class SettingsViewModelTest {

    @Before
    fun resetEngineInit() {
        SettingsViewModel.engineInit = { _, _, _, _, _, _ -> true }
    }

    @After
    fun restoreEngineInit() {
        SettingsViewModel.engineInit = { dbPath, baseURL, apiKey, agentID, version, devCleartextHosts ->
            com.branchdam.mobile.EngineHolder.initialize(
                dbPath = dbPath,
                baseURL = baseURL,
                apiKey = apiKey,
                agentID = agentID,
                version = version,
                devCleartextHosts = devCleartextHosts,
            )
        }
    }

    @Test
    fun testValidateUrlBlankFails() {
        assertEquals("Server URL is required", SettingsViewModel.validateUrl("", isDebug = true))
    }

    @Test
    fun testValidateUrlHttpInReleaseFails() {
        assertNotNull(SettingsViewModel.validateUrl("http://example.com", isDebug = false))
    }

    @Test
    fun testValidateUrlHttpsPasses() {
        assertNull(SettingsViewModel.validateUrl("https://example.com", isDebug = true))
        assertNull(SettingsViewModel.validateUrl("https://example.com", isDebug = false))
    }

    @Test
    fun testValidateUrlLocalDevHostPassesInDebug() {
        assertNull(SettingsViewModel.validateUrl("http://10.0.2.2:8080", isDebug = true))
    }

    @Test
    fun testValidateUrlLocalDevHostFailsInRelease() {
        assertNotNull(SettingsViewModel.validateUrl("http://10.0.2.2:8080", isDebug = false))
    }

    @Test
    fun testEngineInitDefaultIsCallable() {
        // The default engineInit references EngineHolder, which is unavailable
        // in unit tests (the AAR is not on the test classpath). Just verify
        // it's not null and the seam is in place.
        assertNotNull(SettingsViewModel.engineInit)
    }

    @Test
    fun testEngineInitSeamIsInvokable() {
        var called = false
        SettingsViewModel.engineInit = { _, _, _, _, _, _ ->
            called = true
            true
        }
        val result: Boolean = SettingsViewModel.engineInit(
            "dbPath", "https://x", "key", "agent", "0.1.0", "",
        )
        assertTrue(result)
        assertTrue(called)
    }

    @Test
    fun testEngineInitFailurePathReturnsFalse() {
        SettingsViewModel.engineInit = { _, _, _, _, _, _ -> false }
        val result: Boolean = SettingsViewModel.engineInit(
            "dbPath", "https://x", "key", "agent", "0.1.0", "",
        )
        assertFalse(result)
    }

    @Test
    fun testBuildConfigExposesNonEmptyVersion() {
        // BuildConfig.VERSION_NAME / VERSION_CODE are auto-generated by
        // AGP from defaultConfig { versionName / versionCode }, which is
        // what gets baked into the APK and AAB. Asserting the non-empty
        // invariant here keeps a regression — a literal "0.1.0" being
        // reintroduced in BranchDamApplication / EngineHolder /
        // SettingsViewModel — from sneaking back in.
        val name = com.branchdam.mobile.BuildConfig.VERSION_NAME
        val code = com.branchdam.mobile.BuildConfig.VERSION_CODE
        assertTrue("VERSION_NAME must be non-empty", name.isNotEmpty())
        assertTrue("VERSION_CODE must be >= 1", code >= 1)
    }
}
